package com.tu.votingapp.enums;

public enum ElectionType {
    ELECTIONS_FOR_MEMBERS_OF_PARLIAMENT,
    ELECTIONS_FOR_PARLIAMENT_GRAND_ASSEMBLY,
    ELECTIONS_FOR_PRESIDENT_AND_VICE_PRESIDENT,
    ELECTIONS_FOR_EUROPEAN_PARLIAMENT,
    ELECTIONS_FOR_MUNICIPALITY_MEMBERS,
    ELECTIONS_FOR_MUNICIPALITY_MAYOR,
    ELECTIONS_FOR_MUNICIPALITY_MAYOR_LOCATION_REGION,
    ELECTIONS_FOR_MUNICIPALITY_MAYOR_LOCATION
}
